In [1]:
from google.colab import drive
from sklearn.model_selection import train_test_split
from keras import models
import pandas as pd
from keras import layers
import cv2
import numpy as np
from keras.applications.vgg16 import VGG16
from keras import optimizers
from keras.utils import to_categorical
import os

Using TensorFlow backend.


In [2]:
drive.mount("/content/drive", force_remount=True)


Mounted at /content/drive


In [0]:
!unzip "/content/drive/My Drive/splitted.zip" -d "/content/drive/My Drive/splitted"

Archive:  /content/drive/My Drive/splitted.zip
   creating: /content/drive/My Drive/splitted/train/
   creating: /content/drive/My Drive/splitted/train/cardboard/
  inflating: /content/drive/My Drive/splitted/train/cardboard/augmented_image_0.jpg  
  inflating: /content/drive/My Drive/splitted/train/cardboard/augmented_image_1.jpg  
  inflating: /content/drive/My Drive/splitted/train/cardboard/augmented_image_10.jpg  
  inflating: /content/drive/My Drive/splitted/train/cardboard/augmented_image_100.jpg  
  inflating: /content/drive/My Drive/splitted/train/cardboard/augmented_image_1000.jpg  
  inflating: /content/drive/My Drive/splitted/train/cardboard/augmented_image_101.jpg  
  inflating: /content/drive/My Drive/splitted/train/cardboard/augmented_image_102.jpg  
  inflating: /content/drive/My Drive/splitted/train/cardboard/augmented_image_103.jpg  
  inflating: /content/drive/My Drive/splitted/train/cardboard/augmented_image_104.jpg  
  inflating: /content/drive/My Drive/splitted/tra

In [0]:
path= "/content/drive/My Drive/splitted/"

In [4]:
dirs=os.listdir(path)
print(dirs)

['train', 'val', 'test']


In [0]:
GLASS = 0 #3
PAPER = 1 #2
CARDBOARD = 2 #4
PLASTIC = 3 #1
METAL = 4 #6
TRASH = 5 #5

DIM1 = 384
DIM2 = 512

In [14]:
X_test=[]
y_test=[]
X_train=[]
y_train=[]
X_val=[]
y_val=[]
objects=[]
labels=[]
x={'0':2,'1':0,'2':4,'3':1,'4':3}

for file in dirs:
  print(file)
  i=0
  for subfile in os.listdir("/content/drive/My Drive/splitted/"+file): 
    c=0
    
    print(subfile)
    if(i<5):
      for images in os.listdir("/content/drive/My Drive/splitted/"+file+"/"+subfile):
        img1=cv2.imread("/content/drive/My Drive/splitted/"+file+"/"+subfile+"/"+images)
        img1=cv2.resize(img1,(150,150))
        if(c%50==0):
          print(c)
        c=c+1
        if(file=='test'):
          X_val.append(np.asarray(img1))
          y_val.append(x[str(i)])
        if(file=='train'):
          X_train.append(np.asarray(img1))
          y_train.append(x[str(i)])
        if(file=='val'):
          X_val.append(np.asarray(img1))
          y_val.append(x[str(i)])
        
        #objects.append(np.asarray(img1))
        #labels.append(x[str(i)])
    i=i+1

    

train
cardboard
0
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100
1150
1200
1250
1300
1350
1400
glass
0
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100
1150
1200
1250
1300
1350
1400
1450
1500
metal
0
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100
1150
1200
1250
1300
1350
1400
paper
0
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100
1150
1200
1250
1300
1350
1400
1450
1500
1550
plastic
0
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100
1150
1200
1250
1300
1350
1400
1450
val
cardboard
0
50
glass
0
50
metal
0
50
paper
0
50
plastic
0
50
test
cardboard
0
50
glass
0
50
metal
0
50
paper
0
50
plastic
0
50


In [0]:
#y_test=to_categorical(y_test)
#X_test=np.stack( X_test )
y_val=to_categorical(y_val)
X_val=np.stack( X_val )
y_train=to_categorical(y_train)
X_train=np.stack( X_train )

In [17]:
print(y_train.shape)

(7395, 5)


In [0]:
from keras.preprocessing.image import ImageDataGenerator
dataset_path = "/content/drive/My Drive/dataset-resized/"
train_datagen = ImageDataGenerator(
        rotation_range=40,
        width_shift_range=0.2,
        height_shift_range=0.2,
        shear_range=0.2,
        zoom_range=0.2,
        #horizontal_flip=True,
        #fill_mode='nearest',
        validation_split=0.2
)

train_generator = train_datagen.flow_from_directory(
        dataset_path,
        target_size=(128, 128),
        color_mode="rgb",
        batch_size=64,
        class_mode="categorical",
        shuffle=True,
        subset='training')

validation_generator = train_datagen.flow_from_directory(
        dataset_path,
        target_size=(128, 128),
        color_mode="rgb",
        batch_size=32,
        class_mode="categorical",
        shuffle=True,#same as in train generator
        subset='validation')

Found 2024 images belonging to 6 classes.
Found 503 images belonging to 6 classes.


In [0]:
print((np.stack(labels)).shape)

(4902,)


In [0]:
labels=to_categorical(labels)

In [0]:
print(objects[2055].shape)

(128, 128, 3)


In [0]:
obj=np.stack( objects )
print(obj.shape)

(4902, 150, 150, 3)


In [0]:
print(obj.shape)
print(labels.shape)
np.save('objects_data',obj)

(2527, 384, 512, 3)
(2527, 6)


In [0]:
from google.colab import files
#files.download('objects_data.npy')

In [0]:
labels=np.load('/content/drive/My Drive/dataset-resized/objects_labels.npy')

object1=np.load('/content/drive/My Drive/dataset-resized/objects_data.npy')

FileNotFoundError: ignored

In [0]:
print(labels.shape)

(4902, 5)


In [0]:
np.save('objects_labels',labels)
files.download('objects_labels.npy')

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train,y_train, test_size=0.3)

In [0]:
from keras.applications import VGG16
#Load the VGG model
vgg_conv = VGG16(weights='imagenet', include_top=False, input_shape=(150, 150, 3))

In [27]:

from keras.models import Sequential
from keras.optimizers import SGD
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense,BatchNormalization

model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=(150, 150,3)))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.2))
#model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(MaxPooling2D(pool_size=(2, 2)))

#model.add(Conv2D(64, (3, 3)))
#model.add(BatchNormalization())
#model.add(Activation('relu'))
#model.add(Dropout(0.4))
#model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  
#model.add(Dense(1024))
#model.add(Activation('relu'))
#model.add(BatchNormalization())
#model.add(Dropout(0.4))
model.add(Dense(64))
model.add(Activation('relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))
model.add(Dense(5))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer=optimizers.adam(lr=1e-5),
              metrics=['acc'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_11 (Conv2D)           (None, 148, 148, 32)      896       
_________________________________________________________________
batch_normalization_15 (Batc (None, 148, 148, 32)      128       
_________________________________________________________________
activation_19 (Activation)   (None, 148, 148, 32)      0         
_________________________________________________________________
dropout_11 (Dropout)         (None, 148, 148, 32)      0         
_________________________________________________________________
conv2d_12 (Conv2D)           (None, 146, 146, 64)      18496     
_________________________________________________________________
batch_normalization_16 (Batc (None, 146, 146, 64)      256       
_________________________________________________________________
activation_20 (Activation)   (None, 146, 146, 64)      0         
__________

In [29]:
model.fit(X_train, y_train, epochs=20,validation_data=(X_val,y_val), batch_size=250)

Train on 7395 samples, validate on 1000 samples
Epoch 1/20


ResourceExhaustedError: ignored

In [31]:
for layer in vgg_conv.layers[:-4]:
    layer.trainable = False

for layer in vgg_conv.layers:
    print(layer, layer.trainable)

<keras.engine.input_layer.InputLayer object at 0x7f5bcbcfa320> False
<keras.layers.convolutional.Conv2D object at 0x7f5bcbcfae80> False
<keras.layers.convolutional.Conv2D object at 0x7f5bcbc8a8d0> False
<keras.layers.pooling.MaxPooling2D object at 0x7f5bcbc5c940> False
<keras.layers.convolutional.Conv2D object at 0x7f5bcbc5c828> False
<keras.layers.convolutional.Conv2D object at 0x7f5bcbc2aeb8> False
<keras.layers.pooling.MaxPooling2D object at 0x7f5bcbbd36d8> False
<keras.layers.convolutional.Conv2D object at 0x7f5bcbbd35c0> False
<keras.layers.convolutional.Conv2D object at 0x7f5bcbb83358> False
<keras.layers.convolutional.Conv2D object at 0x7f5bcbb9b978> False
<keras.layers.pooling.MaxPooling2D object at 0x7f5bcbbb2a58> False
<keras.layers.convolutional.Conv2D object at 0x7f5bcbbb2ac8> False
<keras.layers.convolutional.Conv2D object at 0x7f5bcbb60c18> False
<keras.layers.convolutional.Conv2D object at 0x7f5bcbb76da0> False
<keras.layers.pooling.MaxPooling2D object at 0x7f5bcbb25c50>

In [32]:
model = models.Sequential()
 
# Add the vgg convolutional base model
model.add(vgg_conv)
 
# Add new layers
model.add(layers.Flatten())
model.add(layers.Dense(1024, activation='relu'))
model.add(layers.Dropout(0.4))
#model.add(layers.Dense(128, activation='relu'))
#model.add(layers.Dropout(0.4))
model.add(layers.Dense(5, activation='softmax'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
vgg16 (Model)                (None, 4, 4, 512)         14714688  
_________________________________________________________________
flatten_6 (Flatten)          (None, 8192)              0         
_________________________________________________________________
dense_11 (Dense)             (None, 1024)              8389632   
_________________________________________________________________
dropout_14 (Dropout)         (None, 1024)              0         
_________________________________________________________________
dense_12 (Dense)             (None, 5)                 5125      
Total params: 23,109,445
Trainable params: 15,474,181
Non-trainable params: 7,635,264
_________________________________________________________________


In [0]:

model.compile(loss='categorical_crossentropy',
              optimizer=optimizers.adam(lr=1e-4),
              metrics=['acc'])

In [0]:
X_train=np.asarray(train_generator)


KeyboardInterrupt: ignored

In [0]:
STEP_SIZE_TRAIN=train_generator.n//train_generator.batch_size
STEP_SIZE_VALID=validation_generator.n//validation_generator.batch_size
model.fit_generator(generator=train_generator,
                    steps_per_epoch=STEP_SIZE_TRAIN,
                    validation_data=validation_generator,
                    validation_steps=STEP_SIZE_VALID,
                    epochs=50,verbose=2
)

In [35]:
model.fit(X_train, y_train, epochs=10,validation_data=(X_val,y_val), batch_size=300)

Train on 7395 samples, validate on 1000 samples
Epoch 1/10
7395/7395 [==============================] - 44s 6ms/step - loss: 3.0797 - acc: 0.4688 - val_loss: 0.9142 - val_acc: 0.6670
Epoch 2/10
7395/7395 [==============================] - 22s 3ms/step - loss: 0.8346 - acc: 0.6868 - val_loss: 0.4239 - val_acc: 0.8430
Epoch 3/10
7395/7395 [==============================] - 22s 3ms/step - loss: 0.4504 - acc: 0.8331 - val_loss: 0.1902 - val_acc: 0.9370
Epoch 4/10
7395/7395 [==============================] - 22s 3ms/step - loss: 0.2360 - acc: 0.9124 - val_loss: 0.0835 - val_acc: 0.9760
Epoch 5/10
7395/7395 [==============================] - 22s 3ms/step - loss: 0.1156 - acc: 0.9586 - val_loss: 0.0435 - val_acc: 0.9880
Epoch 6/10
7395/7395 [==============================] - 22s 3ms/step - loss: 0.0675 - acc: 0.9774 - val_loss: 0.0145 - val_acc: 0.9960
Epoch 7/10
7395/7395 [==============================] - 22s 3ms/step - loss: 0.0409 - acc: 0.9881 - val_loss: 0.0081 - val_acc: 0.9990
Epoch 8

In [36]:
predictions=model.predict(X_val)
acc = model.evaluate(X_val, y_val)
print(acc[1])
model.save("/content/drive/My Drive/FER/fer2013/WSP4_final4.h5")

1000/1000 [==============================] - 3s 3ms/step
0.999


In [0]:
from keras.models import load_model
model=load_model("/content/drive/My Drive/FER/fer2013/WSP2_final2.h5")

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.


In [0]:
from sklearn.metrics import confusion_matrix
y_pred=np.argmax(model.predict(X_test),axis=1)
print(y_pred)
print(confusion_matrix(y_test,y_pred))

[2 3 1 ... 0 2 0]
[[301   0   0   4   5]
 [  1 320   4   1   0]
 [  0   6 259   0   0]
 [  5   4   0 267   5]
 [  8   0   2   0 279]]
